### ISSUE TITLE
Author name is not updated in Webview when it is changed in Legacy

### ISSUE THREAD

**Issue by edwoodward** [Connexions/cnx#200] opened 2018-11-28 21:27 UTC
### Description
When a user name on a Lagacy account is changed, the new name displays forrectly on Legacy, but Webview continues to display the old name. Legacy needs to update the name in the table used by Webview when the name is saved.

**Change or Bug** _Choose the title for the issue or pick the correct lable._

----------------
**Steps to Reproduce the bug or Details about Change:** _What, Who, Where and How?_

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [ ] ` N/A
- **Username:** 
- **URL:**  
- **Course number:**  
- **Course type:**  

- **Steps**
1. Change the name of a user with published content
2. View the published content in Legacy and the new name will be displayed
3. View the same content in Webview and the old name will be displayed
----------------
**Environment:**

- **Instance:**
` [ X] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [ ] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [ ] ` Chrome ` [ ] ` Firefox ` [ ] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

----------------
**Images or Screenshots** (_attach below_)

**Comment by openstaxalina** [comment] 2018-11-30 22:58
This seems to be a duplicate of: https://github.com/Connexions/webview/issues/2081.  I am going to close this issue.

**Closed by openstaxalina** 2018-11-30 22:58 UTC
